### ISSUE TITLE
Allow "running"

### ISSUE THREAD

**Issue by sirkitree** [scenevr/client#126]
Sort of like #16, when you hit the Shift key allow an avatar to move faster.

**Comment by bnolan** [comment]
There is actually running already!

https://github.com/scenevr/client/blob/master/src/environment.js#L19

The problem is that it's only 30% faster than walking, so it's not very obvious. I copied the relative speeds from Minecraft. I'm not sure what the industry-wide standard is for running vs walking, but Janus for example has a much larger ratio between walking and running.

**Comment by sirkitree** [comment]
Is running achieved by holding Shift like Janus? If so I honestly don't notice an increase.

**Comment by bnolan** [comment]
Hmm, you're right, it seems like it's hardly accelerating at all. I'll look into it.

**Comment by bnolan** [comment]
Just deployed to www.scenevr.com - feels faster now. :)

**Comment by sirkitree** [comment]
:clap: I think this is a great improvement. Thanks!
